<?php

declare(strict_types=1);

namespace Blaze\ModelMcp\Tools;

use Blaze\ModelMcp\Registry\ModelDescriptor;
use Blaze\ModelMcp\Registry\ModelRegistry;
use Illuminate\Contracts\Container\Container;
use LogicException;

/**
 * Builds the concrete, model-bound tool instances for every exposed model and
 * operation. The instances are registered on the MCP server's $tools property.
 */
final class ToolFactory
{
    /**
     * Maps each operation to its tool class.
     *
     * @var array<string, class-string<AbstractModelTool>>
     */
    private const TOOLS = [
        'list' => ListModelTool::class,
        'view' => GetModelTool::class,
        'create' => CreateModelTool::class,
        'update' => UpdateModelTool::class,
        'delete' => DeleteModelTool::class,
        'search' => SearchModelTool::class,
    ];

    public function __construct(
        private readonly Container $container,
        private readonly ModelRegistry $registry,
    ) {
        //
    }

    /**
     * @return list<AbstractModelTool>
     *
     * @throws LogicException when two exposed models would generate the same tool name.
     */
    public function make(): array
    {
        $tools = [];
        $owners = [];

        foreach ($this->registry->descriptors() as $descriptor) {
            foreach ($descriptor->operations as $operation) {
                $tool = $this->makeTool($descriptor, $operation);

                if ($tool === null) {
                    continue;
                }

                $name = $tool->name();

                if (isset($owners[$name])) {
                    throw new LogicException(sprintf(
                        'Duplicate MCP tool name [%s] generated by [%s] and [%s]. '
                        .'Give one of them a distinct "name" in config/model-mcp.php.',
                        $name,
                        $owners[$name],
                        $descriptor->modelClass,
                    ));
                }

                $owners[$name] = $descriptor->modelClass;
                $tools[] = $tool;
            }
        }

        return $tools;
    }

    private function makeTool(ModelDescriptor $descriptor, string $operation): ?AbstractModelTool
    {
        $class = self::TOOLS[$operation] ?? null;

        if ($class === null) {
            return null;
        }

        return $this->container->make($class, ['descriptor' => $descriptor]);
    }
}
